/***************************************************************************
* Project:  OpenCPN
* Purpose:  Open Observer Plugin Control Dialog
* Author:   Jon Gough
*
* Project:  OpenCPN
*
***************************************************************************
*   Copyright (C) 2013 by David S. Register                               *
*                                                                         *
*   This program is free software; you can redistribute it and/or modify  *
*   it under the terms of the GNU General Public License as published by  *
*   the Free Software Foundation; either version 2 of the License, or     *
*   (at your option) any later version.                                   *
*                                                                         *
*   This program is distributed in the hope that it will be useful,       *
*   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
*   GNU General Public License for more details.                          *
*                                                                         *
*   You should have received a copy of the GNU General Public License     *
*   along with this program; if not, write to the                         *
*   Free Software Foundation, Inc.,                                       *
*   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301,  USA.         *
**************************************************************************/

#pragma once

/**
 * @file
 * Subclass of ooControlDialogDef, which is generated by wxFormBuilder.
 */

#include <wx/grid.h>

#include "ooControlDialogDef.h"

#include "ooMiniPanel.h"
#include "ooObservations.h"

///////////////////////////////////////////////////////////////////////////////
/// Class ooControlDialogImpl
///////////////////////////////////////////////////////////////////////////////
class ooControlDialogImpl : public ooControlDialogDef
{
public:
        ooControlDialogImpl(wxWindow *parent);
        ~ooControlDialogImpl();

        void NewProject();
        bool LoadProject(const wxString& filename);
        void SaveProject(wxFile *file) const;
        void UseProject();

        void CreateObservationsTable(ooObservations *observations);
        void RestoreBackupObservations();

        void SetPositionFix(time_t fixTime, double lat, double lon);

protected:
        void SetupObservationsForProject();
        void SetupObservationTable(int row_count = -1);

        void OnButtonClickProjectEditUse(wxCommandEvent& event);
        void OnButtonClickProjectNew(wxCommandEvent& event);
        void OnButtonClickProjectLoad(wxCommandEvent& event);
        void OnButtonClickProjectSave(wxCommandEvent& event);
	void OnButtonClickProjectNewColumn(wxCommandEvent& event);
        void OnButtonClickProjectDeleteColumn(wxCommandEvent& event);

        void OnButtonClickNewObservation( wxCommandEvent& event );
        void OnButtonClickDeleteObservation( wxCommandEvent& event );
        void OnButtonClickDeleteAllObservations(wxCommandEvent& event);
        void OnButtonClickExportObservations( wxCommandEvent& event );
        void OnButtonClickObservationsAddMarks( wxCommandEvent& event );
        void OnButtonClickObservationsDeleteMarks( wxCommandEvent& event );

        void ooControlCloseClick(wxCommandEvent& event);
        void ooControlDialogDefOnClose(wxCloseEvent& event);

private:
        void OnBackupTimer(wxTimerEvent& event);

        ooMiniPanel *m_MiniPanel;

        wxString m_BackupFilename;
        wxTimer m_BackupTimer;

        ooObservations * m_Observations;
        wxGrid* m_ObservationsTable;
};
